const INFO={
 'result.guardrails':'For each simulated path, take the median annual funded household living spending over all modelled years. The headline is the median of those path medians. In current-year dollars it is adjusted for inflation; future-dollar mode uses nominal amounts. Survivor spending reductions and shortfalls are included. It is not the starting spending amount.',
 'housing.soldDate':'The date the sale money was paid to you starts the Centrelink home-sale proceeds exemption clock. For sales from 1 January 2023, qualifying replacement-home money can be exempt from the assets test for up to 24 months, with a possible extension. It still attracts deemed income. This field does not add sale proceeds to cash; enter opening cash separately.',
 'housing.homeowner':'This is your homeowner classification for the Centrelink assets test, not simply whether you currently occupy a property. Homeowners have a lower asset-free threshold. Someone temporarily renting after selling a principal home can remain assessed as a homeowner during the qualifying proceeds exemption. Confirm your classification with Services Australia.',
 'housing.extensionVerified':'Tick only when the extension is confirmed for your circumstances. An extra exemption of up to 12 months can apply if you still intend to replace the home, made reasonable attempts promptly, and were delayed by circumstances beyond your control. It is not automatic. The maximum total is 36 months for qualifying sales from 1 January 2023.',
 'housing.exemptionMonths':'Total intended assets-test exemption measured from the old home’s sale settlement. Usually up to 24 months for qualifying sales from 1 January 2023. Above 24 months the model requires the confirmed-extension checkbox; maximum 36 months. Exemption ends when the replacement purchase/build is completed. This is a Centrelink means-test rule, not a tax exemption.',
 'housing.reserved':'Unspent sale proceeds intended for the replacement principal home. The model can exempt qualifying cash from the assets test and deem it at the lower rate while the exemption lasts. It is already part of cash, not a second asset. If opening cash is blank, this supplies a shaded starting suggestion there; add other cash and adjust to the January opening date.',
 'housing.earliest':'The earliest date you reasonably expect to pay the remaining purchase balance. If expected/latest dates are blank, the app suggests two/six months later. These are illustrative planning allowances, not evidence of typical delays or contractual limits. Replace with information from the builder or conveyancer.',
 'housing.expected':'Your central settlement scenario. A shaded date is a suggestion, earliest plus two months. The model uses this in the baseline scenario; earlier or delayed scenarios use the other dates. Edit or confirm before relying on it.',
 'housing.latest':'A plausible delayed settlement scenario, not a guaranteed deadline. A shaded suggestion is earliest plus six months. Add a longer stress case if construction uncertainty warrants it.',
 'housing.balance':'The remaining amount due on settlement, excluding any deposit already paid. The engine deducts this plus separately entered costs once, on the selected settlement date.',
 'housing.deposit':'An amount already paid. Do not include it in opening cash or the remaining purchase balance. The model includes an unsettled deposit in assessable assets as a simplifying assumption; confirm your actual Centrelink treatment.',
 'housing.enabled':'Enable only for a future purchase settlement during the projection. Opening balances must precede the payment; a completed purchase belongs in your opening position.',
 'housing.mainHome':'Whether the new property will be your principal residence. A principal home is generally excluded from the Centrelink assets test; another property is assessable. This app does not determine legal eligibility.',
 'assets.cash':'Opening cash and term deposits at the January projection start. Include unspent sale proceeds once. A shaded suggestion from replacement-home cash is only a starting point, not your total bank balance. Do not also add a dated receipt for money already in this figure.',
 'assets.costBasis':'What you paid for the outside holdings, adjusted as required for tax. The model approximates gains proportionally when selling. It does not track individual tax lots, capital losses or all adjustments.',
 'assets.yield':'Cash distributions as a percentage of invested value each year. They are part of total investment return, not extra return. They move from investments to cash and can create taxable income.',
 'assets.franking':'Percentage of distributions that are franked. The model assumes a 30% company tax rate when estimating credits. Replace this with a verified estimate for the holdings.',
 'assets.ownerShare':'Partner 1’s share of outside investment income and gains for the simplified tax calculation. Partner 2 receives the remainder. This should reflect actual legal/tax ownership.',
 'settings.paths':'Number of stochastic market paths per standard strategy, using the same paths across strategies. Default 1000; editable from 100 to 1500. More paths reduce sampling noise but take longer. They do not remove errors in assumptions.',
 'settings.success':'Required percentage of sampled paths funding all payments and the estate reserve when solving the fixed-spending amount. This is a conditional model success rate, not a forecast probability or guarantee.',
 'settings.guardMax':'Maximum annual guardrails spending as a percentage of starting desired spending, in real terms. Default 200%. This permits increases if the withdrawal-rate rule supports them; it does not target or guarantee doubling.',
 'settings.guardThreshold':'Percentage change in the net withdrawal rate relative to its starting reference that triggers an annual spending adjustment. Higher thresholds mean fewer interventions.',
 'settings.guardStep':'Percentage increase or decrease applied after crossing a guardrail. Cuts stop at essential spending; increases stop at the maximum. Shortfalls still count as failures.',
 'settings.inflation':'Expected annual increase in prices. Spending and indexed pensions grow with simulated inflation. At or below 1% is flagged as a low long-term assumption; test several values.',
 'settings.inflationVol':'Standard deviation of annual inflation shocks, measured in percentage points. Zero fixes inflation at the assumed mean.',
 'settings.correlation':'How strongly different investment options move together. Identical options share shocks. Very low correlation can make diversification look unrealistically effective.',
 'settings.returnShift':'Adds these percentage points to all investment real-return assumptions. Useful for testing weaker markets without editing every allocation.',
 'settings.fx':'Australian dollars received for one British pound before conversion fees. This is an editable planning rate, not a live market quote.',
 'settings.fxVol':'Annual volatility of GBP/AUD in the simulated exchange-rate process. Zero removes currency uncertainty.',
 'settings.benefitIndex':'Hypothetical annual indexation of benefit and means-test thresholds and the DB income cap. Actual policy/indexation can differ.',
 'settings.taxBracketIndex':'Hypothetical annual growth of tax brackets. Default zero keeps brackets nominal. Raising this can reduce projected future tax.',
 'settings.withdrawal':'Order used to fund a cash shortage from accessible assets. It is a simplified rule, not a tax-optimal withdrawal strategy.',
 'settings.dbCap':'Cap controlling age-60 concessions on capped defined benefit pensions. Combined taxable taxed/tax-free portions are considered before untaxed portions. Birthday-year and survivor adjustments are approximate.',
};
const LEAF={
 homeowner:'Centrelink classification affecting asset-test thresholds. A qualifying home-sale proceeds exemption can preserve homeowner status temporarily.',
 costs:'Costs in addition to the purchase/receipt itself. Include fees once, in the stated currency; obtain a quote rather than assume a concession.',
 value:'Estimated property value after completion. This is not automatically available for living expenses without a scheduled sale.',
 extraDelayCost:'Additional monthly expense after expected settlement while settlement is delayed, on top of temporary rent. Do not include a one-off expense as a monthly amount.',
 exemptionMonths:'Centrelink home-sale assets-test exemption period. The rule is not an income-tax exemption.',
 state:'Reference location for your records. The app does not calculate state-based duty concessions; enter quoted costs separately.',
 careAge:'Age when the entered care scenario begins for a living partner. Enable care in Scenarios; the app does not infer care probability.',
 careAnnual:'Extra annual care expense on top of ordinary spending when the care scenario is enabled. Use a verified quote.',
 careLump:'One-off care amount treated as spent. If refundable, enter a later dated receipt rather than assume it is permanently lost.',
 careYears:'Duration of the entered care scenario, not a prediction of care needs.',
 homeSaleAge:'Optional sale of the principal home at Partner 1’s stated age. Enter net proceeds and separate replacement-accommodation expenses.',
 homeSaleNet:'Money available after the scheduled home sale and replacement housing. It is added once when the age trigger is reached.',
 estate:'Financial estate value used in the selected context. For UK inheritance calculations enter gross estate before the separately entered debts and costs; for a final reserve use financial assets excluding the home.',
 nilBand:'UK inheritance-tax allowance entered for this estate. The app does not determine eligibility, gifting effects or tapering.',
 residenceBand:'Additional UK residence allowance entered for a qualifying estate. Eligibility and the large-estate taper require separate verification.',
 transferredBand:'Unused inheritance-tax allowance transferred from an eligible deceased spouse. Enter only a verified available amount.',
 share:'Your share of the net estate after modelled debts, tax and costs, as a percentage. Do not also reduce an already net receipt by the same share.',
 low:'Lower inheritance estimate for the low scenario. Inheritances are omitted entirely in the baseline.',
 high:'Upper inheritance estimate for the high scenario. This does not assign a probability to receiving it.',
 lateDate:'Delayed inheritance receipt date used in the smaller/later scenario, which also reduces the amount by 25%.',
 residentSince:'Date Australian tax residence began. This reference date can matter for foreign-super earnings tax, but the app requires a separately verified calculation.',
 vestedGBP:'Reference value at commencement of Australian residence; not automatically used to infer applicable fund earnings.',
 totalGBP:'Reference whole-fund value at payment; the app does not infer partial-payment tax from this figure.',
 contributionsGBP:'Reference contributions since Australian residence; obtain a verified foreign-super tax calculation.',
 crashChance:'Annual probability used to add severe monthly market shocks on top of ordinary variability in the crash scenario. It is a model assumption, not a market forecast.',
 crashSize:'Extra loss percentage at high-growth risk when an added crash occurs. Lower-volatility options receive smaller shocks.',
 poorYears:'Number of initial years with the extra return penalty in the prolonged-poor-returns scenario.',
 poorPenalty:'Annual percentage-point reduction in assumed returns during the selected poor-return period.',
 pensionDelay:'Extra days of delay added to the UK payment in this scenario. Rounding to months is approximate.',
 fxShock:'Immediate percentage change in the initial AUD-per-GBP rate for this scenario. Negative values reduce the Australian-dollar value of UK receipts.',
 debtPayment:'Monthly repayment for the entered other debt. Payments stop once paid off. Interest and principal are handled separately.',
 mortgagePayment:'Monthly mortgage repayment after settlement; stops when the mortgage is paid off.',

 accessMode:'Default assumes retirement conditions are met at age 60. Age 65 is unrestricted regardless of work. A confirmed manual date overrides the age calculation. This app does not model transition-to-retirement withdrawal limits.',
 accessDate:'Enter a confirmed date when unrestricted access is available. Manual dates stay fixed if the owner or birth date changes. Ordinary account withdrawals before 60 are outside this model.',
 pensionDate:'Blank follows the calculated access date by default. A supplied date overrides this. Starting pension phase affects legal minimum withdrawals and Centrelink assessment; merely being eligible does not actually start a pension with the fund.',
 keepAccumulation:'Tick to retain accumulation phase and suppress pension minimum withdrawals, even after access becomes available. You can still withdraw eligible money for modelled expenses. Pension commencement remains a separate real-world action.',
 dob:'Use the full birth date. Age-based access, pension taxation and government eligibility use this date at monthly resolution.',
 endAge:'Projection horizon, not an estimate of death probability. The final calendar year runs through December. Test a longer horizon to assess longevity risk.',
 deathAge:'Optional scheduled death used only in a survivor projection. Blank keeps the person alive until the planning horizon.',
 priorIncome:'Income received July–December before the January projection start, for initial Australian financial-year tax. Do not include income already modelled from January onward.',
 extraTax:'Additional annual tax provision for liabilities outside the engine. It is a planning allowance, not a calculation of the omitted tax.',
 residenceEligible:'Confirmed eligibility enables Age Pension at the modelled age subject to means tests. Age alone is insufficient; residency conditions must also be met.',
 resident:'The tax engine supports Australian tax residents. Non-resident tax needs a verified external calculation.',
 medicare:'Whether Medicare levy applies in the simplified tax estimate. Eligibility and exemptions require verification.',
 hospital:'The engine does not calculate Medicare levy surcharge. If relevant, use an additional annual tax allowance.',
 real:'Assumed annual real arithmetic total return after investment costs/fund tax, before separately entered administration fees. Real means above inflation; this is not a promised return.',
 vol:'Annual return standard deviation in percent. Zero removes market fluctuations, making outcome ranges misleadingly narrow for risky assets.',
 weight:'Percentage of this portfolio allocated to the option. Weights for each allocation must total 100%.',
 option:'Investment category supplying editable return and volatility assumptions. These generic categories are not all products offered by PSSap.',
 fee:'Annual account administration fee in dollars, in addition to costs already reflected in the assumed investment returns.',
 manualWithdrawal:'Minimum chosen annual withdrawal. Once in pension phase the model also enforces the age-based legal minimum, keeping excess withdrawals as cash/outside investments.',
 gross:'Annual pension before personal tax in plan-start dollars. Enter the pension income, not its capital value. Income follows the commencement assumption and indexing choice.',
 kind:'PSS uses the age-55 retirement assumption when commencement is blank. Other DB schemes have different rules; enter a confirmed date. None excludes this source.',
 free:'Percentage of pension classified tax-free by the fund. It is distinct from the taxable taxed portion, which generally becomes tax-free at 60. All components must sum to 100%.',
 taxed:'Taxable component from a taxed source. Generally assessable below 60 and tax-free from 60, subject to the DB cap and special death-benefit rules. Use fund advice.',
 untaxed:'Taxable component from an untaxed source, generally the unfunded employer benefit. It remains assessable at 60, usually with a capped 10% offset. Use fund advice.',
 deductible:'Percentage deducted from DB gross income for Centrelink income assessment. Capped at 10% in this model. It is not a personal income-tax deduction.',
 survivor:'Percentage retained after a partner’s death. Pension survivor percentages reflect scheme terms; spending percentage reflects household costs. Fixed costs often fall less than household size.',
 verified:'Confirm only after checking the underlying terms/calculation. A tick records your verification; it does not verify the information itself.',
 indexed:'Increase pension with simulated inflation. Actual CPI adjustment dates and scheme rules may differ.',
 essential:'Annual minimum living expenditure. Housing charges, tax and dated events entered elsewhere are additional.',
 desired:'Annual starting living-spending target for phases and guardrails. The fixed strategy separately solves supported spending at your success target.',
 reserve:'Emergency cash target retained before investing excess cash. It remains a spendable asset, not an additional expense.',
 estate:'Required final financial assets in January-start purchasing power, excluding the home and net of modelled debt. Failing this reserve counts as failure even without earlier shortfalls.',
 year:'Calendar year when this change takes effect. Allocation changes start in January; spending phases apply from that calendar year.',
 multiplier:'Percentage of initial desired spending retained during this phase, before inflation. A value below essential needs can cause the strategy to be unsupported.',
 amount:'Amount in the stated currency or January-start dollars as labelled. Events inflate until payment; do not enter the same payment in opening balances and future receipts.',
 repeat:'Whole number of years between repeated payments. Zero means a single payment.',
 taxMode:'Select verified Australian tax treatment for the UK lump sum. Unresolved treatment deducts a provisional 30% reserve, not a verified tax liability.',
 afeGBP:'Verified applicable fund earnings attributable to this payment, in GBP. The app does not infer the amount from reference records.',
 manualTax:'Australian tax provision in AUD, separate from UK withholding. Account for any verified foreign-tax credit in your estimate.',
 withholdingGBP:'Tax withheld in the UK, deducted separately. Refunds should be represented as dated receipts; do not assume a refund automatically.',
 processingDays:'Planning delay added to the UK scheduled payment date. Monthly rounding is approximate and cannot guarantee cash arrives before settlement.',
 reductionGBP:'Annual reduction to the ongoing UK pension once the scheduled lump-sum payment occurs. Enter the scheme’s quoted trade-off.',
 lumpGBP:'Gross expected UK lump sum in pounds before withholding, Australian tax reserve and currency conversion fees.',
 ongoingGBP:'Annual continuing UK pension in pounds. Held constant in GBP in this model unless you revise it; Australian-dollar amounts fluctuate with exchange rates.',
 stateGBP:'Annual UK State Pension in pounds from the confirmed commencement date. Usually not uprated annually for Australian residents.',
 rent:'Enter the stated monthly/annual amount. Temporary rent and property income are separate; housing costs should not also be counted in living expenditure.',
 strata:'Annual strata charges added separately to living spending after settlement. One-off special levies belong in dated expenses.',
 mortgage:'Confirmed loan amount received at settlement. It provides cash and creates equal debt, not net wealth.',
 bridge:'Confirmed temporary finance available at settlement. It creates debt; an unapproved credit amount should not be treated as funding.',
};
export function fieldExplanation(path,label,hint=''){return INFO[path]||LEAF[path.split('.').at(-1)]||hint||`${label} is part of your entered plan. Use the amount/date and units shown; blank amounts mean unknown and can be provisionally excluded. Review Help for model assumptions and enter a verified value where available.`;}
// Date: 2026-10-09. Model: GPT-6. Prompt: Explain financial inputs in accessible pop-up help, especially home-sale exemptions, homeowner status, assumptions and pension terminology.
