import {RULES,PRESETS,defaults,VERSION} from './rules.js';
import {validDate,inputErrors,inputWarnings} from './input-checks.js';
export {inputErrors} from './input-checks.js';
export const n=v=>Number.isFinite(Number(v))?Number(v):0;
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const monthCache=new Map();
export function month(s){if(monthCache.has(s))return monthCache.get(s);const value=validDate(s)?Number(s.slice(0,4))*12+Number(s.slice(5,7))-1:null;if(monthCache.size>2000)monthCache.clear();monthCache.set(s,value);return value;}
export function dateOf(m){return `${Math.floor(m/12)}-${String(m%12+1).padStart(2,'0')}-01`;}
export function age(dob,m){const b=month(dob);return b===null?0:(m-b)/12;}
export function calendarPlan(d){d.start=`${new Date().getFullYear()}-01-01`;return d;}
export function dbAnnual(p,m){return p.db.kind==='None'||m<(month(p.db.start)??-Infinity)?0:n(p.db.gross);}
export const minRate=a=>a<65?.04:a<75?.05:a<80?.06:a<85?.07:a<90?.09:a<95?.11:.14;
export function incomeTax(taxable,year,index=1){const x=Math.max(0,taxable),b=[18200,45000,135000,190000].map(v=>v*index),r=year>=2027?.14:year>=2026?.15:.16;return Math.max(0,Math.min(Math.max(x-b[0],0),b[1]-b[0])*r+Math.min(Math.max(x-b[1],0),b[2]-b[1])*.3+Math.min(Math.max(x-b[2],0),b[3]-b[2])*.37+Math.max(x-b[3],0)*.45);}
export function taxBill(x,year,opts={}){x=Math.max(0,x);const ind=opts.index||1;let lito=x<=37500*ind?700: x<=45000*ind?Math.max(0,700-(x-37500*ind)*.05):Math.max(0,325-(x-45000*ind)*.015);
 const sapto=opts.senior?Math.max(0,(opts.single?2230:1602)-Math.max(0,x-(opts.single?32279:28974)*ind)*.125):0;
 const base=Math.max(0,incomeTax(x,year,ind)-lito-sapto-n(opts.offset));
 const threshold=n(opts.medicareThreshold)||28500;let levy=opts.medicare===false?0:Math.min(.02*x,Math.max(0,(x-threshold)*.1));
 if(opts.familyLevy!==undefined)levy=opts.familyLevy;return base+levy-n(opts.franking);}
export function agePension({financial,assets,otherIncome,eligible,homeowner=true,single=false,index=1,reserved=0}){if(!eligible)return 0;const max=(single?RULES.singleMax:RULES.coupleMax)*index,free=(single?RULES.singleAssets:RULES.coupleAssets)*index+(homeowner?0:RULES.nonHomeExtra*index),deem=(single?RULES.deemSingle:RULES.deemCouple)*index;
 const income=otherIncome+Math.min(financial,deem)*RULES.deemLow+Math.max(0,financial-deem)*RULES.deemHigh+reserved*RULES.deemLow;
 const byIncome=max-Math.max(0,income-(single?RULES.singleIncome:RULES.coupleIncome)*index)*(single?.5:.25);
 const byAssets=max-Math.max(0,assets-free)*.003*26*(single?1:.5);return Math.max(0,Math.min(max,byIncome,byAssets));}
export function mixStats(rows,settings){let mean=0,varr=0;const ws=rows.map(x=>n(x.weight)/100),vs=rows.map(x=>n(x.vol)/100);rows.forEach((r,i)=>{mean+=ws[i]*(n(r.real)+n(settings.inflation)+n(settings.returnShift))/100;rows.forEach((q,j)=>{varr+=ws[i]*ws[j]*vs[i]*vs[j]*(i===j||r.option===q.option?1:n(settings.correlation));});});return {mean,vol:Math.sqrt(varr)};}
export function inheritanceNet(e,fx){let amount=n(e.amount);if(e.mode==='estate'){const estate=Math.max(0,n(e.estate)-n(e.debts)),allow=n(e.nilBand)+n(e.residenceBand)+n(e.transferredBand);const tax=Math.max(0,estate-allow)*n(e.taxRate)/100;amount=Math.max(0,estate-tax-n(e.costs))*n(e.share)/100;}return amount*(e.currency==='GBP'?fx:1);}
export function warnings(d){const w=[];d.people.forEach((p,i)=>{if(!p.dob)w.push(`${p.label}: date of birth is missing.`);if(!p.resident)w.push(`${p.label}: non-resident Australian taxation is not supported. Enter an annual tax adjustment and obtain a verified projection.`);if(p.residenceEligible!=='yes')w.push(`${p.label}: Age Pension residence eligibility is unconfirmed; no Age Pension is included.`);if(p.db.gross===null)w.push(`${p.label}: pension amount is unknown; provisionally zero.`);if(n(p.db.gross)>0&&!p.db.verified)w.push(`${p.label}: verify pension components and survivor percentage.`);if(n(p.db.gross)>0&&Math.abs(n(p.db.free)+n(p.db.taxed)+n(p.db.untaxed)-100)>.01)w.push(`${p.label}: pension tax components must total 100%.`);if(p.uk.scheme!=='none'&&p.uk.lumpGBP===null)w.push(`${p.label}: UK lump-sum amount is unknown; provisionally excluded. Select None if there is no UK pension.`);if(n(p.uk.lumpGBP)>0&&(p.uk.taxMode==='unknown'||!p.uk.verified))w.push(`${p.label}: UK lump-sum tax is unresolved. A provisional 30% reserve is deducted; results are not a verified tax estimate.`);if(n(p.uk.lumpGBP)>0&&!p.uk.date)w.push(`${p.label}: UK payment date is missing; the lump sum is not included.`);if(!p.hospital)w.push(`${p.label}: Medicare levy surcharge is not automatic; enter an annual additional tax allowance if applicable.`);});
 if(d.assets.cash===null||d.assets.outside===null)w.push('Cash or outside investments are unknown; provisionally zero.');if(d.assets.costBasis===null&&n(d.assets.outside)>0)w.push('Investment cost basis is unknown; all withdrawals are conservatively treated as gains.');if(d.spending.essential===null||d.spending.desired===null)w.push('Enter essential and desired annual spending.');
 if(d.housing.enabled&&(!d.housing.expected||d.housing.balance===null))w.push('Apartment settlement date or balance is missing.');
 for(const a of d.accounts){if(Math.abs(a.mix.reduce((s,r)=>s+n(r.weight),0)-100)>.01)w.push(`${a.label}: investment allocation must total 100%.`);if(a.balance===null)w.push(`${a.label}: balance is unknown.`);if(a.type==='unknown'||a.type==='smsf')w.push(`${a.label}: modelled as standard accumulation until its treatment is verified; SMSF-specific tax is not modelled.`);if(a.type==='pension'&&age(d.people[a.owner].dob,month(d.start))<60)w.push(`${a.label}: pension withdrawals before age 60 are unsupported; no withdrawals until 60.`);if(!a.accessDate&&a.type!=='pension')w.push(`${a.label}: access date is missing; no withdrawals before age 65.`);for(const c of a.changes)if(Math.abs(c.mix.reduce((s,r)=>s+n(r.weight),0)-100)>.01)w.push(`${a.label}: future allocation for ${c.year} must total 100%.`);}
 if(Math.abs(d.assets.mix.reduce((s,r)=>s+n(r.weight),0)-100)>.01)w.push('Outside investment allocation must total 100%.');
 for(const c of d.contributions){if(c.type==='ncc'&&n(c.amount)>RULES.nccCap)w.push('A contribution exceeds the ordinary annual non-concessional cap. Personal bring-forward eligibility must be verified.');}if(d.contributions.some(c=>!c.verified))w.push('A proposed super contribution has not been checked for eligibility/caps; it is excluded.');if(d.inheritances.some(e=>e.mode==='estate'))w.push('UK estate calculator is a simplified allowance calculation. Trusts, gifts, tapering and inherited-pension income tax require verified net receipts.');if(d.accounts.some(a=>n(a.balance)>3000000))w.push('High-balance super additional taxes require an annual tax adjustment; this engine does not calculate Division 296.');if(d.accounts.some(a=>n(a.balance)>RULES.transferCap&&a.type==='pension'))w.push('A pension account exceeds the general transfer balance cap; confirm personal cap and pension/accumulation split.');return [...new Set([...inputWarnings(d),...w])];}
export function validate(d){if(!d||d.schema!==1||!Array.isArray(d.people)||d.people.length!==2)throw Error('This is not a Retirement Horizons backup.');const size=JSON.stringify(d).length;if(size>2000000)throw Error('Backup is too large.');for(const p of d.people)if(p?.db&&p.db.start===undefined)p.db.start='';const base=defaults();function shape(v,b,path='plan'){if(b&&typeof b==='object'&&!Array.isArray(b)){if(!v||typeof v!=='object'||Array.isArray(v))throw Error(`Backup has incomplete ${path}.`);for(const [k,x] of Object.entries(b)){if(v[k]===undefined)throw Error(`Backup is missing ${path}.${k}.`);shape(v[k],x,path+'.'+k);}}else if(typeof b==='number'&&v!==null&&(typeof v!=='number'||!Number.isFinite(v)))throw Error(`Backup has invalid ${path}.`);else if(b===null&&v!==null&&!path.endsWith('.lastBackup')&&(typeof v!=='number'||!Number.isFinite(v)))throw Error(`Backup has invalid ${path}.`);else if(typeof b==='boolean'&&typeof v!=='boolean')throw Error(`Backup has invalid ${path}.`);}shape(d,base);d.people.forEach(p=>shape(p,base.people[0],'partner'));for(const key of Object.keys(base))if(d[key]===undefined)throw Error(`Backup is missing ${key}.`);for(const k of ['accounts','inheritances','contributions'])if(!Array.isArray(d[k])||d[k].length>100)throw Error('Too many entries.');function inspect(x){if(typeof x==='number'&&!Number.isFinite(x))throw Error('Invalid numeric value.');if(x&&typeof x==='object')for(const k of Object.keys(x)){if(['__proto__','constructor','prototype'].includes(k))throw Error('Invalid backup field.');inspect(x[k]);}}inspect(d);for(const p of d.people){if(!p||typeof p.label!=='string'||!p.db||!p.uk||typeof p.dob!=='string')throw Error('Incomplete partner details in backup.');}for(const a of [d.assets,...d.accounts]){if(!a||!Array.isArray(a.mix)||!Array.isArray(a.changes))throw Error('Incomplete allocation in backup.');for(const allocation of [a.mix,...a.changes.map(c=>c.mix)]){if(!Array.isArray(allocation)||allocation.length>30||allocation.some(r=>!r||typeof r.option!=='string'||!Object.hasOwn(PRESETS,r.option)||n(r.weight)<0||n(r.weight)>100||n(r.vol)<0||n(r.vol)>50))throw Error('Invalid allocation in backup.');}}if(!d.housing||!d.spending||!Array.isArray(d.spending.events)||!Array.isArray(d.spending.phases)||!d.settings||!d.scenario||month(d.start)===null)throw Error('Incomplete plan in backup.');return d;}
const FACTORS=Object.keys(PRESETS).length+4;
function rng(seed){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
function normal(random){return Math.sqrt(-2*Math.log(Math.max(1e-9,random())))*Math.cos(2*Math.PI*random());}
function horizon(d){const start=month(d.start);const remaining=Math.max(...d.people.map(p=>n(p.endAge)-age(p.dob,start)));return clamp(start%12===0?Math.ceil(remaining)*12:Math.ceil(remaining*12),12,720);}
export function paths(d,count){const months=horizon(d),r=rng(n(d.settings.seed));return Array.from({length:count},()=>{const z=new Float32Array(months*FACTORS);for(let m=0;m<months;m++){for(let j=0;j<FACTORS;j++)z[m*FACTORS+j]=normal(r);if(d.scenario.stress==='crashes'&&r()<n(d.settings.crashChance)/1200)z[m*FACTORS+FACTORS-1]= -100;}return z;});}
function weightsAt(a,year){const c=a.changes.filter(c=>n(c.year)<=year).sort((x,y)=>n(y.year)-n(x.year))[0];return c?c.mix:a.mix;}
function optionShock(option,z,m){const i=Math.max(0,Object.keys(PRESETS).indexOf(option));return z[m*FACTORS+1+i];}
function growth(rows,d,z,m){const c=clamp(n(d.settings.correlation),0,.99),common=z[m*FACTORS];let ret=0;for(const row of rows){const annual=(n(row.real)+n(d.settings.inflation)+n(d.settings.returnShift)-(d.scenario.stress==='poor'&&m<n(d.settings.poorYears)*12?n(d.settings.poorPenalty):0))/100;const shock=Math.sqrt(c)*common+Math.sqrt(1-c)*optionShock(row.option,z,m);let q=annual/12+n(row.vol)/100/Math.sqrt(12)*shock;if(d.scenario.stress==='crashes'&&z[m*FACTORS+FACTORS-1]===-100)q-=n(d.settings.crashSize)/100*Math.min(1,n(row.vol)/15);ret+=n(row.weight)/100*q;}return clamp(ret,-.85,.8);}
function sum(a){return a.reduce((s,x)=>s+x,0);}
export function simulate(d,strategy,spend,z,{detail=false,reassess=false,check=null}={}){const start=month(d.start),months=horizon(d),s=d.settings,h=d.housing;let cash=n(d.assets.cash),out=n(d.assets.outside),cost=n(d.assets.costBasis),debt=n(d.assets.debt),mortgage=0,bridge=0,settled=!h.enabled,home=n(h.value),infl=1,fx=n(s.fx)*(1+n(d.scenario.fxShock)/100),failed=false,essentialFail=false,settlementFail=false,spendReal=spend,initialAssets=Math.max(1,cash+out+sum(d.accounts.map(a=>n(a.balance)))-(h.enabled?n(h.balance)+n(h.costs):0)),guardRate=0,guardCuts=0,lastTax=0;
 const acc=d.accounts.map(a=>({...a,balance:n(a.balance)})),alive=[true,true];const ys=new Map(),fyRecords=new Map();let fyCurrent=-1,fyStartBalances=[],minimumRemaining=[],monthlyDraw=0,pendingTax=0,pendingShortfall=0;
 let annualReview=spend,referenceWithdrawal=Math.max(1,spend-sum(d.people.map(p=>dbAnnual(p,start)-taxBill(dbAnnual(p,start)*(n(p.db.untaxed)+(age(p.dob,start)<60?n(p.db.taxed):0))/100,Math.floor(start/12)-(start%12<6?1:0),{offset:age(p.dob,start)>=60?dbAnnual(p,start)*n(p.db.untaxed)/100*.1:0,medicare:p.medicare}))));guardRate=referenceWithdrawal/initialAssets;
 const deathMonths=d.people.map((p,i)=>{if(d.scenario.survivor===String(i)&&d.scenario.deathYear)return n(d.scenario.deathYear)*12;return p.deathAge!==null?month(p.dob)+n(p.deathAge)*12:Infinity;});
 const settle=month(h[d.scenario.timing]||h.expected),ukDates=d.people.map(p=>month(p.uk.date)===null?null:month(p.uk.date)+Math.ceil((n(p.uk.processingDays)+n(d.scenario.pensionDelay))/30));
 function eligibleAcc(a,m){return alive[a.owner]&&age(d.people[a.owner].dob,m)>=60&&(m>=(month(a.accessDate)??(a.type==='pension'?start:month(d.people[a.owner].dob)+65*12)));}
 function takeAcc(a,amount,m){if(!eligibleAcc(a,m))return 0;const v=Math.min(a.balance,Math.max(0,amount));a.balance-=v;monthlyDraw+=v;const i=acc.indexOf(a),pm=month(a.pensionDate)??(a.type==='pension'?start:Infinity);if(m>=pm&&minimumRemaining[i]!==undefined)minimumRemaining[i]=Math.max(0,minimumRemaining[i]-v);return v;}
 function takeOut(amount){const v=Math.min(out,Math.max(0,amount)),gain=out>0?Math.max(0,1-cost/out)*v:0;cost=out>0?cost*(1-v/out):0;out-=v;cash+=v;monthlyDraw+=v;return gain;}
 function fund(amount,m){let gain=0,need=Math.max(0,amount-cash);const useSuper=()=>{for(const a of acc){const v=takeAcc(a,need,m);cash+=v;need-=v;}};if(s.withdrawal==='super-first')useSuper();if(need>0){gain+=takeOut(need);need=Math.max(0,amount-cash);}if(need>0&&s.withdrawal!=='super-first')useSuper();return gain;}
 function reconcile(rec,year,m,row){let due=fiscalTax(rec,year)-rec.provision;for(let j=0;j<24;j++){const gain=fund(Math.max(0,due),m);if(gain<=.0001)break;for(let i=0;i<2;i++)rec.taxable[i]+=gain*(d.assets.discount?.5:1)*(alive.filter(Boolean).length===1?(alive[i]?1:0):(i===0?n(d.assets.ownerShare)/100:1-n(d.assets.ownerShare)/100));due=fiscalTax(rec,year)-rec.provision;}cash-=due;if(cash<-.01){failed=true;if(row)row.shortfall+=-cash;else pendingShortfall+=-cash;cash=0;}if(row)row.tax+=due;return due;}
 function fiscalTax(rec,year){const index=Math.pow(1+n(s.taxBracketIndex)/100,Math.max(0,year-2026));const x=rec.taxable;const senior=rec.senior;const single=rec.single;const individual=x.map((v,i)=>d.people[i].medicare?Math.min(.02*v,Math.max(0,(v-n(s[senior[i]?'medicareSenior':'medicareSingle']))*.1)):0);if(!single){const threshold=n(s[senior.some(Boolean)?'medicareSeniorFamily':'medicareFamily']),familyCap=Math.min(.02*sum(x),Math.max(0,(sum(x)-threshold)*.1));if(sum(individual)>familyCap&&sum(x)>0)for(let i=0;i<2;i++)individual[i]=familyCap*x[i]/sum(x);}
 return sum(x.map((v,i)=>taxBill(v,year,{index,offset:rec.offset[i],senior:senior[i],single,medicare:d.people[i].medicare,familyLevy:individual[i],franking:rec.franking?.[i]||0})))+rec.extra;}
 for(let k=0;k<months;k++){monthlyDraw=0;const m=start+k,year=Math.floor(m/12),calMonth=m%12,fy=year+(calMonth>=6?1:0),ages=d.people.map(p=>age(p.dob,m));
 if(k%12===0&&k>0){const annualInfl=clamp(n(s.inflation)+n(s.inflationVol)*z[k*FACTORS+FACTORS-3],-2,12)/100;infl*=1+annualInfl;}
 fx*=Math.exp(-.5*Math.pow(n(s.fxVol)/100,2)/12+n(s.fxVol)/100/Math.sqrt(12)*z[k*FACTORS+FACTORS-2]);
 for(let i=0;i<2;i++)if(alive[i]&&m>=deathMonths[i]){alive[i]=false;for(const a of acc)if(a.owner===i){a.owner=1-i; a.accessDate=dateOf(m);a.pensionDate=a.type==='pension'?dateOf(m):a.pensionDate;} }
 if(!alive.some(Boolean)){if(start%12===0){const last=Array.from(ys.values()).at(-1);if(last)last.months=12;}break;}
 if(fyCurrent!==fy){if(fyCurrent!==-1){const r=fyRecords.get(fyCurrent);pendingTax=reconcile(r,fyCurrent-1,m,null);}
 fyCurrent=fy;fyStartBalances=acc.map(a=>a.balance);minimumRemaining=acc.map((a,i)=>{const pm=month(a.pensionDate)??(a.type==='pension'?start:Infinity),from=Math.max(m,pm),end=fy*12+6;return pm<=m?fyStartBalances[i]*minRate(ages[a.owner])*clamp((end-from)/12,0,1):0;});fyRecords.set(fy,{taxable:[0,0],offset:[0,0],franking:[0,0],provision:0,senior:ages.map((a,i)=>a>=67&&d.people[i].residenceEligible==='yes'),single:alive.filter(Boolean).length===1,extra:0});if(k===0){const rr=fyRecords.get(fy);rr.taxable=d.people.map(p=>n(p.priorIncome));rr.provision=sum(d.people.map(p=>taxBill(n(p.priorIncome),fy-1,{medicare:p.medicare})));}}
 let row=ys.get(year);if(!row){if(check)check();if(!detail)ys.clear();row={year,age1:ages[0],age2:ages[1],months:0,infl,spending:0,target:0,essential:0,db:0,uk:0,other:0,agePension:0,tax:0,withdrawals:0,events:0,shortfall:0,assets:0,accessible:0,cash:0,super:0,outside:0,home:0,debt:0,guardCuts:0,cshc:false};ys.set(year,row);}row.months++;row.tax+=pendingTax;row.shortfall+=pendingShortfall;pendingTax=0;pendingShortfall=0;
 const bi=Math.pow(1+n(s.benefitIndex)/100,k/12),taxable=[0,0],offset=[0,0],franking=[0,0],taxedDB=[0,0],deathOffset=[0,0];let guaranteed=0,dbIncome=0,ukIncome=0,other=0,dbAssess=0;
 for(let i=0;i<2;i++){const p=d.people[i],receiver=alive[i]?i:1-i;if(!alive[receiver])continue;const ratio=alive[i]?1:n(p.db.survivor)/100,gross=(alive[i]||deathMonths[i]>=(month(p.db.start)??start)?dbAnnual(p,m):0)*(p.db.indexed?infl:1)*ratio/12;guaranteed+=gross;dbIncome+=gross;dbAssess+=gross*12*(1-Math.min(.1,n(p.db.deductible)/100));
 const aged=ages[receiver]>=60||(!alive[i]&&age(p.dob,deathMonths[i])>=60);if(aged)taxedDB[receiver]+=gross*(n(p.db.free)+n(p.db.taxed))/100;taxable[receiver]+=gross*(n(p.db.untaxed)+(aged?0:n(p.db.taxed)))/100;offset[receiver]+=aged?gross*n(p.db.untaxed)/100*.1:0;
 // Under-60 dependant death pensions have a 15% offset on the taxed element.
 if(!alive[i]&&!aged)deathOffset[receiver]+=gross*n(p.db.taxed)/100*.15;
 if(alive[i]&&month(p.uk.ongoingStart)!==null&&m>=month(p.uk.ongoingStart)){const u=Math.max(0,n(p.uk.ongoingGBP)-(ukDates[i]!==null&&m>=ukDates[i]?n(p.uk.reductionGBP):0))*fx/12;ukIncome+=u;guaranteed+=u;taxable[i]+=u;}
 else if(!alive[i]&&month(p.uk.ongoingStart)!==null&&m>=month(p.uk.ongoingStart)){const u=Math.max(0,n(p.uk.ongoingGBP)-(ukDates[i]!==null&&m>=ukDates[i]?n(p.uk.reductionGBP):0))*n(p.uk.survivor)/100*fx/12;ukIncome+=u;guaranteed+=u;taxable[receiver]+=u;}
 if(alive[i]&&month(p.uk.stateStart)!==null&&m>=month(p.uk.stateStart)){const u=n(p.uk.stateGBP)*fx/12;ukIncome+=u;guaranteed+=u;taxable[i]+=u;}
 if(alive[i]&&(!p.otherIncomeEnd||m<=month(p.otherIncomeEnd))){const o=n(p.otherIncome)*infl/12;other+=o;guaranteed+=o;taxable[i]+=o*n(p.taxableOther)/100;}
 if(alive[i]&&ukDates[i]===m){const grossGBP=n(p.uk.lumpGBP),gross=grossGBP*fx*(1-n(s.fxFee)/100),withheld=n(p.uk.withholdingGBP)*fx;let tax=p.uk.taxMode==='unknown'||!p.uk.verified?gross*.3:p.uk.taxMode==='manual'?n(p.uk.manualTax):0;if(p.uk.taxMode==='afe'&&p.uk.verified){taxable[i]+=Math.min(grossGBP,n(p.uk.afeGBP))*fx;}
 cash+=gross-withheld-tax;row.events+=gross-withheld-tax;}
 }
 for(let i=0;i<2;i++){const cap=n(s.dbCap)*bi/12;taxable[i]+=Math.max(0,taxedDB[i]-cap)*.5;offset[i]=Math.min(offset[i],Math.max(0,cap-taxedDB[i])*.1)+deathOffset[i];}cash+=guaranteed;
 const reserve= !settled&&h.enabled&&h.soldDate&&m>=month(h.soldDate)&&m<month(h.soldDate)+Math.min(h.extensionVerified?n(h.exemptionMonths):24,36)?Math.min(Math.max(0,cash),n(h.reserved)):0;
 const financial=Math.max(0,cash-reserve)+out+sum(acc.filter(a=>ages[a.owner]>=67||m>=(month(a.pensionDate)??(a.type==='pension'?start:Infinity))).map(a=>a.balance));
 const assessAssets=financial+n(d.assets.otherAssets)+n(d.assets.propertyValue)+(!h.mainHome&&settled?home:0)+Math.max(0,n(h.deposit))*(settled?0:1);
 const assessIncome=dbAssess+ukIncome*12+other*12+n(d.assets.rent)-n(d.assets.propertyCost);
 let ap=0;for(let i=0;i<2;i++){if(alive[i]&&ages[i]>=67&&d.people[i].residenceEligible==='yes'){const a=agePension({financial,assets:assessAssets,otherIncome:assessIncome,eligible:true,homeowner:h.enabled&&settled?h.mainHome:h.homeowner,single:alive.filter(Boolean).length===1,index:bi,reserved:reserve})/12;ap+=a;taxable[i]+=a*(alive.filter(Boolean).length===1?RULES.singleBasic/RULES.singleMax:RULES.coupleBasic/RULES.coupleMax);}}cash+=ap;
 const interest=Math.max(0,cash)*n(s.cashRate)/1200,rent=(n(d.assets.rent)-n(d.assets.propertyCost))*infl/12,outGrowth=out*growth(weightsAt(d.assets,year),d,z,k),distribution=Math.min(Math.max(0,out+outGrowth),out*n(d.assets.yield)/1200);cash+=interest+rent+distribution;
 // Total-return growth includes distributions. Deduct the cash distribution to avoid double counting.
 out=Math.max(0,out+outGrowth-distribution);const frank=distribution*n(d.assets.franking)/100*.3/.7;for(let i=0;i<2;i++){const share=alive.filter(Boolean).length===1?(alive[i]?1:0):(i===0?n(d.assets.ownerShare)/100:1-n(d.assets.ownerShare)/100);taxable[i]+=(interest+distribution+rent+frank)*share;franking[i]+=frank*share;}
 for(let ai=0;ai<acc.length;ai++){const a=acc[ai],startPension=month(a.pensionDate)??(a.type==='pension'?start:Infinity);if(m===startPension){const end=fy*12+6;minimumRemaining[ai]=m%12===5?0:a.balance*minRate(ages[a.owner])*clamp((end-m)/12,0,1);}a.balance=Math.max(0,a.balance*(1+growth(weightsAt(a,year),d,z,k))-n(a.fee)/12);const pm=month(a.pensionDate)??(a.type==='pension'?start:Infinity);if(m>=pm&&eligibleAcc(a,m)){const remaining=Math.max(1,fy*12+6-m);const v=takeAcc(a,Math.max(minimumRemaining[ai]/remaining,n(a.manualWithdrawal)*infl/12),m);cash+=v;}}
 if(h.enabled&&!settled&&m===settle){mortgage=n(h.mortgage);bridge=n(h.bridge);cash+=mortgage+bridge;let gain=fund(n(h.balance)+n(h.costs),m);cash-=n(h.balance)+n(h.costs);if(cash<-.01){settlementFail=true;failed=true;row.shortfall+=-cash;cash=0;}settled=true;home=n(h.value);for(let i=0;i<2;i++)taxable[i]+=gain*(d.assets.discount?.5:1)*(i===0?n(d.assets.ownerShare)/100:1-n(d.assets.ownerShare)/100);}
 if(d.scenario.inheritance!=='none')for(let ei=0;ei<d.inheritances.length;ei++){const e=d.inheritances[ei];if(!['all','late','low','high'].includes(d.scenario.inheritance)&&d.scenario.inheritance!==String(ei))continue;const at=month(d.scenario.inheritance==='late'?e.lateDate:e.date);if(at===m){const entry={...e};if(d.scenario.inheritance==='low'&&e.low!==null){entry.mode='net';entry.amount=e.low;}if(d.scenario.inheritance==='high'&&e.high!==null){entry.mode='net';entry.amount=e.high;}const v=inheritanceNet(entry,fx)*(d.scenario.inheritance==='late'?.75:1)*(e.currency==='GBP'?1-n(s.fxFee)/100:1);cash+=v;row.events+=v;}}
 for(const c of d.contributions)if(c.verified&&month(c.date)===m){const a=acc[n(c.account)];if(a){const amount=Math.min(n(c.amount),Math.max(0,cash-n(d.spending.reserve)-(settled?0:n(h.balance)+n(h.costs))));cash-=amount;a.balance+=amount;row.events-=amount;}}
 let event=0;for(const e of d.spending.events){const at=month(e.date);if(at!==null&&(at===m||(n(e.repeat)>0&&m>at&&(m-at)%(n(e.repeat)*12)===0))){const v=n(e.amount)*infl;event+=(e.kind==='receipt'?-1:1)*v;}}
 if(d.scenario.care&&ages.some((a,i)=>alive[i]&&a>=n(d.spending.careAge)&&a<n(d.spending.careAge)+n(d.spending.careYears))){event+=n(d.spending.careAnnual)*infl/12;if(ages.some((a,i)=>alive[i]&&a>=n(d.spending.careAge)&&a<n(d.spending.careAge)+1/12))event+=n(d.spending.careLump)*infl;}
 if(d.spending.homeSaleAge!==null&&ages[0]>=n(d.spending.homeSaleAge)&&ages[0]<n(d.spending.homeSaleAge)+1/12){cash+=n(d.spending.homeSaleNet)*infl;home=0;}
 const singles=alive.filter(Boolean).length===1,survFactor=singles?n(d.spending.survivor)/100:1;
 if(k%12===0&&k>0){if(strategy==='guardrails'){const port=Math.max(1,cash+out+sum(acc.map(a=>a.balance))-(settled?0:n(h.balance)+n(h.costs))),withdrawal=Math.max(1,spendReal*infl-guaranteed*12-ap*12+lastTax*12),rate=withdrawal/port,th=n(s.guardThreshold)/100;
 if(rate>guardRate*(1+th)){spendReal=Math.max(n(d.spending.essential),spendReal*(1-n(s.guardStep)/100));guardCuts++;}else if(rate<guardRate*(1-th)){spendReal=Math.min(spend*n(s.guardMax)/100,spendReal*(1+n(s.guardStep)/100));}}
 if(strategy==='reassessment'){// Rolling conditional search uses current balances and fresh, deterministic future paths, never the realised future.
 const future=structuredClone(d);future.start=dateOf(m);future.assets.cash=cash;future.assets.outside=out;future.assets.costBasis=cost;future.accounts=acc.map(a=>({...a}));future.housing.enabled=!settled&&h.enabled;future.housing.mortgage=mortgage;future.settings.paths=12;future.settings.seed=n(s.seed)+k*97;future.inheritances=future.inheritances.filter(e=>month(e.date)>m);future.spending.events=future.spending.events.filter(e=>month(e.date)>m||n(e.repeat)>0);future.people.forEach(p=>{if(month(p.uk.date)<=m){p.uk.lumpGBP=0;p.uk.ongoingGBP=Math.max(0,n(p.uk.ongoingGBP)-n(p.uk.reductionGBP));p.uk.reductionGBP=0;}});const proposed=solve(future,'fixed',paths(future,12),6,check)/infl;annualReview=clamp(proposed,annualReview*.9,annualReview*1.1);}}
 const phase=d.spending.phases.filter(p=>n(p.year)<=year).sort((a,b)=>n(b.year)-n(a.year))[0];const targetReal=(strategy==='phases'?spend*(phase?n(phase.multiplier)/100:1):strategy==='guardrails'?spendReal:strategy==='reassessment'?annualReview:spend)*survFactor;
 const essential=n(d.spending.essential)*infl*survFactor/12,target=targetReal*infl/12;
 const temporary=!settled&&h.enabled?(n(h.rent)+(m>(month(h.expected)??Infinity)?n(h.extraDelayCost):0))*infl:0,strata=h.enabled&&settled?n(h.strata)*infl/12:0;
 let payDebt=0;for(const which of ['debt','mortgage','bridge']){let bal=which==='debt'?debt:which==='mortgage'?mortgage:bridge,rate=which==='debt'?n(d.assets.debtRate):which==='mortgage'?n(h.mortgageRate):n(h.bridgeRate);if(bal>0){bal*=1+rate/1200;const pay=which==='bridge'?Math.min(bal,Math.max(0,cash-target-n(d.spending.reserve))):Math.min(bal,which==='debt'?n(d.assets.debtPayment):n(h.mortgagePayment));bal-=pay;payDebt+=pay;}if(which==='debt')debt=bal;else if(which==='mortgage')mortgage=bal;else bridge=bal;}
 const expenses=target+temporary+strata+event+payDebt;
 let gain=fund(expenses,m);const gainsTax=gain*(d.assets.discount?.5:1);for(let i=0;i<2;i++)taxable[i]+=gainsTax*(singles?(alive[i]?1:0):(i===0?n(d.assets.ownerShare)/100:1-n(d.assets.ownerShare)/100));
 const rec=fyRecords.get(fy);for(let i=0;i<2;i++){rec.taxable[i]+=Math.max(0,taxable[i]);rec.offset[i]+=offset[i];rec.franking[i]+=franking[i];}rec.single=singles;rec.extra+=sum(d.people.filter((p,i)=>alive[i]).map(p=>n(p.extraTax)))/12;
 // Accrue financial-year tax on actual income to date. A one-off receipt is never annualised as recurring income.
 rec.senior=rec.senior.map((v,i)=>v||(ages[i]>=67&&d.people[i].residenceEligible==='yes'));
 let tax=Math.max(0,fiscalTax(rec,fy-1)-rec.provision);
 for(let j=0;j<24;j++){const extraGain=fund(expenses+tax,m);if(extraGain<=.0001)break;for(let i=0;i<2;i++)rec.taxable[i]+=extraGain*(d.assets.discount?.5:1)*(singles?(alive[i]?1:0):(i===0?n(d.assets.ownerShare)/100:1-n(d.assets.ownerShare)/100));tax=Math.max(0,fiscalTax(rec,fy-1)-rec.provision);}
 rec.provision+=tax;
 lastTax=tax;const available=Math.max(0,cash-tax-temporary-strata-event-payDebt),actualSpend=Math.min(target,available);const short=Math.max(0,expenses+tax-cash);if(short>.01){failed=true;row.shortfall+=short;}if(actualSpend+1<essential)essentialFail=true;cash=Math.max(0,cash-expenses-tax);
 // Sweep excess cash beyond settlement + emergency reserve to outside investments.
 const retain=n(d.spending.reserve)+(settled?0:n(h.balance)+n(h.costs));if(cash>retain){const v=cash-retain;cash-=v;out+=v;cost+=v;}
 row.withdrawals+=monthlyDraw;row.spending+=actualSpend;row.target+=target;row.essential+=essential;row.db+=dbIncome;row.uk+=ukIncome;row.other+=other+interest+distribution+rent;row.agePension+=ap;row.tax+=tax;row.events-=event;row.assets=cash+out+sum(acc.map(a=>a.balance));row.accessible=cash+out+sum(acc.filter(a=>eligibleAcc(a,m)).map(a=>a.balance));row.cash=cash;row.super=sum(acc.map(a=>a.balance));row.outside=out;row.home=home;row.debt=debt+mortgage+bridge;row.guardCuts=guardCuts;
 const ati=sum(taxable)*12+Math.min(sum(acc.filter(a=>m>=(month(a.pensionDate)??Infinity)).map(a=>a.balance)),RULES.deemCouple)*RULES.deemLow+Math.max(0,sum(acc.filter(a=>m>=(month(a.pensionDate)??Infinity)).map(a=>a.balance))-RULES.deemCouple)*RULES.deemHigh;row.cshc=ages.some((a,i)=>alive[i]&&a>=67&&d.people[i].residenceEligible==='yes')&&ati<(singles?RULES.cshcSingle:RULES.cshcCouple)*bi;
 }
 const lastRec=fyRecords.get(fyCurrent);if(lastRec){const row=Array.from(ys.values()).at(-1);reconcile(lastRec,fyCurrent-1,start+months-1,row);if(row){row.assets=cash+out+sum(acc.map(a=>a.balance));row.cash=cash;row.super=sum(acc.map(a=>a.balance));row.outside=out;row.accessible=cash+out+sum(acc.filter(a=>eligibleAcc(a,start+months-1)).map(a=>a.balance));}}
 const endAssets=cash+out+sum(acc.map(a=>a.balance))-debt-mortgage-bridge;return {success:!failed&&!essentialFail&&endAssets/infl>=n(d.spending.estate),essentialSuccess:!essentialFail,settlementSuccess:!settlementFail,endAssets:endAssets/infl,guardCuts,rows:detail?Array.from(ys.values()):[]};}
export function solve(d,strategy,zs,iterations=11,check=null){const ok=amount=>zs.reduce((s,z)=>{if(check)check();return s+Number(simulate(d,strategy,amount,z,{check}).success);},0)/zs.length>=n(d.settings.success)/100;const endYear=Math.floor((month(d.start)+horizon(d)-1)/12),floorRatio=strategy==='phases'?Math.min(1,...d.spending.phases.filter(p=>p.year<=endYear).map(p=>n(p.multiplier)/100)):1;if(floorRatio<=0&&n(d.spending.essential)>0)return null;let lo=n(d.spending.essential)/(floorRatio||1),hi=Math.max(lo*2,250000,n(d.spending.desired)*3,sum(d.people.map(p=>n(p.db.gross)))*3);if(!ok(lo))return null;while(hi<10000000&&ok(hi)){lo=hi;hi=Math.min(10000000,hi*2);}for(let j=0;j<iterations;j++){const mid=(lo+hi)/2;if(ok(mid))lo=mid;else hi=mid;}return lo;}
export function quantile(arr,q){if(!arr.length)return 0;const a=arr.slice().sort((a,b)=>a-b),i=(a.length-1)*q;return a[Math.floor(i)]+(a[Math.ceil(i)]-a[Math.floor(i)])*(i%1);}
const RESULT_FIELDS=['spending','target','essential','db','uk','other','agePension','tax','withdrawals','events','shortfall','assets','accessible','cash','super','outside','home','debt'];
export function compare(d,progress=()=>{},advanced=false,{timeLimitMs=advanced?30000:180000}={}){validate(d);const errors=inputErrors(d);if(errors.length)throw Error(errors.join('\n'));const deadline=performance.now()+timeLimitMs;
 const check=()=>{if(performance.now()>deadline)throw Error('Calculation stopped at the device time limit. Your answers are saved. Reduce Simulation paths to 100, or use the three standard strategies instead of annual reassessment. No partial result is shown.');};
 check();const count=advanced?Math.min(25,n(d.settings.paths)):clamp(n(d.settings.paths),100,1500),zs=paths(d,count),strategies=advanced?['reassessment']:['fixed','phases','guardrails'],results=[];
 for(const strategy of strategies){check();progress(`Calculating ${strategy}…`);const safe=strategy==='reassessment'?solve(d,'fixed',zs,9,check):solve(d,strategy,zs,11,check);const requested=strategy==='fixed'?(safe??n(d.spending.essential)):n(d.spending.desired);
 // Retain numeric columns, rather than every simulated household's row objects.
 const columns=new Map(),estates=new Float64Array(count),cuts=new Float64Array(count);let success=0,desiredSuccess=0,essentialSuccess=0,settlementSuccess=0;
 for(let i=0;i<count;i++){check();const run=simulate(d,strategy,requested,zs[i],{detail:true,check});success+=Number(run.success);essentialSuccess+=Number(run.essentialSuccess);settlementSuccess+=Number(run.settlementSuccess);estates[i]=run.endAssets;cuts[i]=run.guardCuts;
 for(const row of run.rows){let c=columns.get(row.year);if(!c){c={meta:{year:row.year,months:row.months,age1:row.age1,age2:row.age2},size:0,values:Object.fromEntries([...RESULT_FIELDS,'infl','cshc'].map(f=>[f,new Float64Array(count)]))};columns.set(row.year,c);}const j=c.size++;for(const field of RESULT_FIELDS)c.values[field][j]=row[field]/row.infl;c.values.infl[j]=row.infl;c.values.cshc[j]=Number(row.cshc);}
 desiredSuccess+=Number(strategy==='fixed'?simulate(d,'fixed',n(d.spending.desired),zs[i],{check}).success:run.success);
 if(i%25===0)progress(`Calculating ${strategy}: ${i+1} of ${count} paths…`);}
 const rows=Array.from(columns.values(),c=>{const result={...c.meta};for(const field of RESULT_FIELDS){const vals=c.values[field].subarray(0,c.size);result[field]=quantile(vals,.5);result[field+'10']=quantile(vals,.1);result[field+'90']=quantile(vals,.9);}result.infl=quantile(c.values.infl.subarray(0,c.size),.5);result.cshc=sum(c.values.cshc.subarray(0,c.size))/c.size;return result;});
 results.push({strategy,safe,start:requested,success:success/count,desiredSuccess:desiredSuccess/count,essentialSuccess:essentialSuccess/count,settlementSuccess:settlementSuccess/count,medianEstate:quantile(estates,.5),cuts:quantile(cuts,.5),rows,count});}
 return {results,warnings:[...warnings(d),...results.filter(r=>r.safe===null).map(r=>`${r.strategy}: no starting spending at or above essential costs meets the selected success target. Inspect settlement, debts, estate reserve and spending needs.`)],version:VERSION,created:new Date().toISOString()};}
export function settlement(d){const start=month(d.start),months=24,h=d.housing,output=[];for(const timing of ['earliest','expected','latest']){let cash=n(d.assets.cash),min=cash,short=0,settled=false;const rows=[];for(let k=0;k<months;k++){const m=start+k;let income=sum(d.people.map(p=>dbAnnual(p,m)+((!p.otherIncomeEnd||m<=month(p.otherIncomeEnd))?n(p.otherIncome):0)))/12,expense=n(d.spending.desired)/12+(settled?n(h.strata)/12:n(h.rent)+(m>(month(h.expected)??Infinity)?n(h.extraDelayCost):0));const tax=sum(d.people.map(p=>taxBill(dbAnnual(p,m)*(n(p.db.untaxed)+(age(p.dob,m)<60?n(p.db.taxed):0))/100+((!p.otherIncomeEnd||m<=month(p.otherIncomeEnd))?n(p.otherIncome)*n(p.taxableOther)/100:0),Math.floor(m/12)-(m%12<6?1:0),{medicare:p.medicare,offset:age(p.dob,m)>=60?Math.min(dbAnnual(p,m)*n(p.db.untaxed)/100,Math.max(0,n(d.settings.dbCap)-dbAnnual(p,m)*(n(p.db.free)+n(p.db.taxed))/100))*.1:0})))/12;cash+=income-tax-expense+cash*n(d.settings.cashRate)/1200;for(const p of d.people){const at=month(p.uk.date);if(at!==null&&m===at+Math.ceil((n(p.uk.processingDays)+n(d.scenario.pensionDelay))/30)){const gross=n(p.uk.lumpGBP)*n(d.settings.fx)*(1+n(d.scenario.fxShock)/100)*(1-n(d.settings.fxFee)/100);const t=p.uk.taxMode==='manual'&&p.uk.verified?n(p.uk.manualTax):gross*.3;cash+=gross-t-n(p.uk.withholdingGBP)*n(d.settings.fx);}}if(h.enabled&&m===month(h[timing]||h.expected)){cash+=n(h.mortgage)+n(h.bridge)-n(h.balance)-n(h.costs);settled=true;short=Math.max(0,-cash);}min=Math.min(min,cash);rows.push({date:dateOf(m),cash,settled});}output.push({timing,rows,minimum:min,shortfall:short});}return output;}
// Date: 2026-10-06. Model: GPT-6. Prompt: Implement the retirement PWA's monthly Australian/UK financial model, uncertainty, fixed/phased/guardrail comparisons, allocation schedules and offline calculations.

// Date: 2026-10-06. Model: GPT-6. Prompt: Fix misleading edge cases in retirement simulations: invalid inputs, tax shortfalls, minimum pension withdrawals, depleted distributions, unsupportable spending and independent market shocks.

// Date: 2026-10-07. Model: GPT-6. Prompt: Rewrite the README for iPad/iPhone users with a prominent education and entertainment disclaimer and live address; rename Pensions to Defined benefit and UK pensions; investigate and reduce browser crashes.

// Date: 2026-10-07. Model: GPT-6. Prompt: Increase the default stochastic run count from 400 to 1500, including existing plans on the former default, with consistent bounds and runtime safeguards.

// Date: 2026-10-07. Model: GPT-6. Prompt: Review PSS survivor percentage, age-55 access and partial-year income; clarify periods, add commencement dates and correct related pension assumptions.

// Date: 2026-10-07. Model: GPT-6. Prompt: Keep the published 67% survivor default and start projections on 1 January of the current year with complete calendar-year results.
