import test from 'node:test';import assert from 'node:assert/strict';
import {defaults,demo} from '../rules.js';import {incomeTax,agePension,mixStats,simulate,paths,settlement,compare,validate,month,inputErrors,warnings,solve,calendarPlan} from '../model.js';
function base(){const d=defaults();d.start='2026-07-01';d.people.forEach(p=>{p.dob='1966-07-01';p.endAge=61;p.residenceEligible='no';p.db.gross=0;p.db.verified=true;p.medicare=false;});d.assets.cash=100000;d.assets.outside=0;d.assets.costBasis=0;d.spending.essential=0;d.spending.desired=0;d.spending.reserve=0;d.settings.inflation=0;d.settings.inflationVol=0;d.settings.fxVol=0;d.settings.cashRate=0;d.assets.yield=0;d.assets.mix=[{option:'cash',weight:100,real:0,vol:0}];return d;}
const zero=d=>new Float32Array(paths(d,1)[0].length);
test('Enacted resident first-band tax changes use financial-year commencement',()=>{assert.equal(incomeTax(45000,2026),4020);assert(Math.abs(incomeTax(45000,2027)-3752)<1e-8);assert.equal(incomeTax(18200,2026),0);});
test('Age Pension couples use combined assets with one eligible member',()=>{const p={financial:0,assets:499000,otherIncome:0,eligible:true};assert.equal(agePension(p),933*26);assert.equal(agePension({...p,assets:599000}),933*26-3900);assert.equal(agePension({...p,eligible:false}),0);});
test('Means test uses deeming instead of actual investment yield',()=>{assert(agePension({financial:500000,assets:500000,otherIncome:0,eligible:true})<933*26);});
test('Mix volatility uses covariance',()=>{const d=base();d.settings.correlation=0;const s=mixStats([{option:'a',weight:50,real:4,vol:10},{option:'b',weight:50,real:4,vol:10}],d.settings);assert(Math.abs(s.vol-Math.sqrt(.005))<1e-8);});
test('Zero-return cash funds precisely the requested payments',()=>{const d=base();const r=simulate(d,'fixed',12000,zero(d),{detail:true});assert(r.success);assert(Math.abs(r.endAssets-88000)<.01);assert.equal(r.rows[0].months,6);assert.equal(r.rows[0].spending,6000);});
test('Distributions are not double counted against total return',()=>{const d=base();d.assets.cash=0;d.assets.outside=100000;d.assets.costBasis=100000;d.assets.yield=6;d.assets.mix[0].real=12;const r=simulate(d,'fixed',0,zero(d));assert(Math.abs(r.endAssets-100000*1.01**12)<1);});
test('Account pension minima move assets to cash/outside without consuming them',()=>{const d=base();d.assets.cash=0;d.accounts=[{label:'Test',owner:0,type:'pension',balance:100000,accessDate:d.start,pensionDate:d.start,fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0}];const r=simulate(d,'fixed',0,zero(d),{detail:true});assert(Math.abs(r.endAssets-100000)<1);assert(r.rows.at(-1).outside>0);assert(r.rows.at(-1).super<100000);});
test('Future allocation schedule applies in the specified January',()=>{const d=base();d.people.forEach(p=>p.endAge=62);d.assets.cash=0;d.assets.outside=100000;d.assets.costBasis=100000;const before=simulate(d,'fixed',0,zero(d));d.assets.changes=[{year:2027,mix:[{option:'cash',weight:100,real:12,vol:0}]}];assert(simulate(d,'fixed',0,zero(d)).endAssets>before.endAssets);});
test('Pending settlement cannot be funded by a later UK receipt',()=>{const d=base();d.assets.cash=10000;d.housing.enabled=true;d.housing.balance=50000;d.housing.expected='2026-08-01';d.housing.earliest='2026-08-01';d.people[0].uk.lumpGBP=50000;d.people[0].uk.date='2026-10-01';d.people[0].uk.taxMode='manual';d.people[0].uk.verified=true;assert(!simulate(d,'fixed',0,zero(d)).settlementSuccess);assert(settlement(d)[0].shortfall>0);});
test('Inheritance is absent in baseline, and included once in smaller/later scenario',()=>{const d=base();d.inheritances=[{amount:10000,mode:'net',currency:'AUD',date:'2026-08-01',lateDate:'2026-09-01'}];assert.equal(simulate(d,'fixed',0,zero(d)).endAssets,100000);d.scenario.inheritance='late';assert.equal(simulate(d,'fixed',0,zero(d)).endAssets,107500);});
test('Unfunded essential-spending floor is recorded as failure',()=>{const d=base();d.assets.cash=0;d.spending.essential=10000;assert(!simulate(d,'guardrails',10000,zero(d)).essentialSuccess);});
test('Mortgage repayments stop when paid off',()=>{const d=base();d.assets.debt=100;d.assets.debtRate=0;d.assets.debtPayment=1000;assert.equal(simulate(d,'fixed',0,zero(d)).endAssets,99900);});
test('Backups reject an invalid schema',()=>{assert.throws(()=>validate({schema:2}));assert.equal(validate(base()).schema,1);});
test('Comparison is deterministic with fixed seed',()=>{const d=demo();d.people.forEach(p=>p.endAge=62);d.settings.paths=100;const a=compare(d),b=compare(d);assert.deepEqual(a.results,b.results);});
// Date: 2026-10-06. Model: GPT-6. Prompt: Validate consequential retirement calculations including tax, means tests, settlement timing, withdrawal conservation and allocation changes.

test('Low inflation and deterministic invested returns produce explicit warnings',()=>{const d=base();d.settings.inflation=1;d.assets.outside=50000;const w=warnings(d);assert(w.some(x=>x.includes('low long-term assumption')));assert(w.some(x=>x.includes('zero market fluctuations')));assert.equal(inputErrors(d).length,0);});
test('Invalid calendar dates and planning ages cannot silently roll over',()=>{assert.equal(month('2026-02-30'),null);assert.equal(month('2026-13-01'),null);const d=base();d.people[0].endAge=59;assert(inputErrors(d).some(x=>x.includes('planning end age')));});
test('Missing or past settlement is blocked instead of omitted',()=>{const d=base();d.housing.enabled=true;d.housing.balance=50000;assert(inputErrors(d).some(x=>x.includes('expected settlement date')));d.housing.expected='2026-06-01';assert(inputErrors(d).some(x=>x.includes('settlement is before')));});
test('Contradictory date order, essential budget and duplicate schedules are blocked',()=>{const d=base();d.housing.enabled=true;d.housing.balance=0;d.housing.expected='2026-08-01';d.housing.earliest='2026-09-01';d.spending.essential=20000;d.spending.desired=10000;d.assets.changes=[{year:2027,mix:d.assets.mix},{year:2027,mix:d.assets.mix}];const es=inputErrors(d);assert(es.some(x=>x.includes('Earliest settlement')));assert(es.some(x=>x.includes('Desired spending')));assert(es.some(x=>x.includes('two allocation changes')));});
test('Selected inheritance requires an amount and scenario date',()=>{const d=base();d.inheritances=[{label:'Family',mode:'net',amount:null,date:'',lateDate:''}];d.scenario.inheritance='late';const es=inputErrors(d);assert(es.some(x=>x.includes('receipt date')));assert(es.some(x=>x.includes('expected net amount')));});
test('Invalid owners, dangling contributions and fractional recurrence are blocked',()=>{const d=base();d.accounts=[{label:'Super',owner:3,type:'accumulation',balance:100,mix:d.assets.mix,changes:[],accessDate:'',pensionDate:''}];d.contributions=[{account:5,amount:100,date:'2026-08-01'}];d.spending.events=[{label:'Expense',date:'2026-08-01',amount:100,repeat:.5}];const es=inputErrors(d);assert(es.some(x=>x.includes('valid owner')));assert(es.some(x=>x.includes('existing account')));assert(es.some(x=>x.includes('whole number of years')));});
test('No supported essential spending is reported as null, not safe zero',()=>{const d=base();d.assets.cash=0;d.spending.essential=10000;d.spending.desired=10000;assert.equal(solve(d,'fixed',[zero(d)]),null);const r=compare(d);assert.equal(r.results[0].safe,null);assert.equal(r.results[0].success,0);assert(r.warnings.some(x=>x.includes('no starting spending')));});
test('Fixed and phased payments below essential needs fail success',()=>{const d=base();d.spending.essential=20000;assert.equal(simulate(d,'fixed',10000,zero(d)).success,false);d.spending.phases=[{year:2026,multiplier:40}];assert.equal(simulate(d,'phases',30000,zero(d)).success,false);});
test('Spending solver expands the initial high bracket for a wealthy household',()=>{const d=base();d.assets.cash=2000000;const s=solve(d,'fixed',[zero(d)],14);assert(s>1900000);assert(s<=2000000);});
test('Withdrawals for settlement reduce remaining annual pension minimum',()=>{const d=base();d.assets.cash=0;d.housing.enabled=true;d.housing.expected=d.start;d.housing.balance=20000;d.accounts=[{label:'Test',owner:0,type:'pension',balance:100000,accessDate:d.start,pensionDate:d.start,fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0}];const r=simulate(d,'fixed',0,zero(d),{detail:true});assert(Math.abs(r.rows.at(-1).super-80000)<.01);assert(Math.abs(r.endAssets-80000)<.01);});
test('June pension commencement needs no minimum in its initial year',()=>{const d=base();d.people.forEach(p=>p.endAge=62);d.accounts=[{label:'Test',owner:0,type:'accumulation',balance:100000,accessDate:d.start,pensionDate:'2027-06-01',fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0}];const r=simulate(d,'fixed',0,zero(d),{detail:true});assert.equal(r.rows[0].withdrawals,0);assert(Math.abs(r.rows[1].withdrawals-2000)<.01);});
test('Commencement minimum uses the balance at pension start',()=>{const d=base();d.assets.cash=0;d.accounts=[{label:'Test',owner:0,type:'accumulation',balance:100000,accessDate:d.start,pensionDate:'2027-01-01',fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0}];d.spending.events=[{label:'Prior withdrawal',date:'2026-08-01',amount:20000,kind:'expense',repeat:0}];const r=simulate(d,'fixed',0,zero(d),{detail:true});assert(Math.abs(r.rows.at(-1).super-78400)<.01);});
test('Unfunded terminal tax bill records failure and a shortfall',()=>{const d=base();d.assets.cash=0;d.people[0].db.gross=50000;d.people[0].priorIncome=200000;const r=simulate(d,'fixed',42000,zero(d),{detail:true});assert.equal(r.success,false);assert(r.rows.some(y=>y.shortfall>0));});
test('Distribution cannot manufacture wealth after a severe loss',()=>{const d=base();d.assets.cash=0;d.assets.outside=100000;d.assets.costBasis=100000;d.spending.reserve=1e9;d.assets.yield=1000;d.assets.mix[0].vol=50;const z=zero(d);z.fill(-100);const r=simulate(d,'fixed',0,z);assert(r.endAssets<=100000);assert(r.endAssets>=0);});
test('Non-homeowner thresholds apply without a pending purchase',()=>{const d=base();d.people.forEach(p=>{p.dob='1959-07-01';p.endAge=68;p.residenceEligible='yes';});d.assets.cash=600000;d.spending.reserve=1e9;d.housing.homeowner=false;const a=simulate(d,'fixed',0,zero(d),{detail:true});d.housing.homeowner=true;const b=simulate(d,'fixed',0,zero(d),{detail:true});assert(a.rows[0].agePension>b.rows[0].agePension);});
test('Disabled housing retains no hidden strata charges',()=>{const d=base();d.housing.enabled=false;d.housing.strata=12000;assert.equal(simulate(d,'fixed',0,zero(d)).endAssets,100000);});
test('Invalid numerical assumptions are rejected before worker calculation',()=>{const d=base();d.settings.paths=0;d.settings.fx=0;d.assets.mix[0].weight=-100;assert.throws(()=>compare(d));});
test('Partially malformed backups are rejected without entering the model',()=>{const d=base();delete d.settings.fx;assert.throws(()=>validate(d),/missing/);});
// Date: 2026-10-06. Model: GPT-6. Prompt: Test realistic input mistakes and financial edge cases, including optimistic assumptions, omitted settlement, unaffordable essentials, pension minimums and tax shortfalls.
test('Phased solver raises its starting floor to fund later essential spending',()=>{const d=base();d.spending.essential=12000;d.spending.desired=20000;d.spending.phases=[{year:2026,multiplier:80}];const safe=solve(d,'phases',[zero(d)]);assert(safe!==null);assert(safe>=15000);assert(simulate(d,'phases',safe,zero(d)).essentialSuccess);});
test('Current pension at age 60 is accessible without a redundant access date',()=>{const d=base();d.assets.cash=0;d.accounts=[{label:'Test',owner:0,type:'pension',balance:100000,accessDate:'',pensionDate:'',fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0}];assert(simulate(d,'fixed',12000,zero(d)).success);});
test('One-off foreign earnings tax is accrued once rather than annualised monthly',()=>{const d=base();d.assets.cash=0;d.people[0].uk.lumpGBP=50000;d.people[0].uk.afeGBP=10000;d.people[0].uk.taxMode='afe';d.people[0].uk.verified=true;d.people[0].uk.processingDays=0;d.people[0].uk.date=d.start;d.settings.fx=2;const r=simulate(d,'fixed',0,zero(d),{detail:true});assert(r.success);assert(Math.abs(r.rows.reduce((s,y)=>s+y.tax,0))<.01);assert(Math.abs(r.endAssets-99000)<.01);});
// Date: 2026-10-06. Model: GPT-6. Prompt: Check phase-floor feasibility, implicit existing-pension access and one-off UK applicable-fund-earnings tax accrual.
test('Ongoing UK income cannot silently vanish when its start date is missing',()=>{const d=base();d.people[0].uk.ongoingGBP=10000;d.people[1].uk.stateGBP=5000;const es=inputErrors(d);assert(es.some(x=>x.includes('continuing UK pension')));assert(es.some(x=>x.includes('start date for UK State')));});
test('UK estate allowances cannot be used accidentally with AUD estate figures',()=>{const d=base();d.inheritances=[{label:'Estate',mode:'estate',currency:'AUD'}];assert(inputErrors(d).some(x=>x.includes('in GBP')));});
// Date: 2026-10-06. Model: GPT-6. Prompt: Test missing UK pension start dates and inheritance currency mistakes.

test('Compact aggregation preserves per-year percentiles and success rates',()=>{
 const d=base();d.people.forEach(p=>p.endAge=63);d.assets.cash=220000;d.spending.essential=15000;d.spending.desired=25000;d.settings.paths=100;d.settings.inflation=2.5;d.settings.inflationVol=1;
 const result=compare(d),zs=paths(d,100);
 for(const r of result.results){const runs=zs.map(z=>simulate(d,r.strategy,r.start,z,{detail:true}));assert.equal(r.success,runs.filter(x=>x.success).length/100);for(const row of r.rows){const values=runs.map(x=>x.rows.find(y=>y.year===row.year)).filter(Boolean);for(const f of ['spending','assets','tax','shortfall']){const a=values.map(x=>x[f]/x.infl).sort((a,b)=>a-b);const q=p=>{const i=(a.length-1)*p;return a[Math.floor(i)]+(a[Math.ceil(i)]-a[Math.floor(i)])*(i%1);};assert.equal(row[f],q(.5));assert.equal(row[f+'10'],q(.1));assert.equal(row[f+'90'],q(.9));}}}
});
test('Summary-only simulations preserve detailed outcomes across tax years',()=>{
 const d=base();d.people.forEach(p=>p.endAge=64);d.assets.cash=300000;d.people[0].otherIncome=12000;d.people[0].medicare=true;const z=paths(d,1)[0];const detailed=simulate(d,'fixed',35000,z,{detail:true}),summary=simulate(d,'fixed',35000,z);assert.deepEqual(summary,{...detailed,rows:[]});
});
test('Time budgets reject standard and advanced work without returning partial results',()=>{
 const d=base();for(const advanced of [false,true])assert.throws(()=>compare(d,()=>{},advanced,{timeLimitMs:0}),/device time limit/);
 const check=()=>{throw Error('Stopped nested work');};assert.throws(()=>simulate(d,'reassessment',10000,zero(d),{detail:true,check}),/Stopped nested work/);assert.throws(()=>solve(d,'fixed',paths(d,1),6,check),/Stopped nested work/);
});
// Date: 2026-10-07. Model: GPT-6. Prompt: Verify compact aggregation keeps simulation results unchanged and calculation budgets stop work without presenting partial results.

test('Standard comparisons actually use all 1500 requested stochastic paths',()=>{
 const d=base();d.settings.paths=1500;d.spending.desired=10000;assert.equal(inputErrors(d).length,0);const result=compare(d);assert(result.results.every(r=>r.count===1500));assert.equal(defaults().settings.paths,1000);d.settings.paths=1501;assert(inputErrors(d).some(e=>e.includes('paths')));
});
// Date: 2026-10-07. Model: GPT-6. Prompt: Verify the requested 1500-path stochastic sample is used without the former 1000-path clamp.

test('PSS default follows the published spouse-only rate and old backups retain their terms',()=>{
 assert.equal(defaults().people[0].db.survivor,67);const d=base();delete d.people[0].db.start;d.people[0].db.survivor=70;const loaded=validate(d);assert.equal(loaded.people[0].db.start,'');assert.equal(loaded.people[0].db.survivor,70);
});
test('PSS pays at 55 and 59; October start is three months, not an age-60 gate',()=>{
 for(const age of [55,59]){const d=base();d.start='2026-10-01';d.people.forEach(p=>{p.dob=`${2026-age}-10-01`;p.endAge=age+2;});d.people[0].db.gross=70000;const r=simulate(d,'fixed',0,zero(d),{detail:true});assert.equal(r.rows[0].months,3);assert(Math.abs(r.rows[0].db-17500)<.01);assert(Math.abs(r.rows[1].db-70000)<.01);}
});
test('Explicit DB commencement applies to both retirement and settlement projections',()=>{
 const d=base();d.people[0].db.gross=70000;d.people[0].db.start='2027-01-01';const r=simulate(d,'fixed',0,zero(d),{detail:true});assert.equal(r.rows[0].db,0);assert(Math.abs(r.rows[1].db-35000)<.01);const cash=settlement(d)[0].rows;assert.equal(cash[0].cash,100000);assert.equal(cash[5].cash,100000);assert(cash[6].cash>100000);
});
test('Contradictory absent pension and invalid commencement are blocked',()=>{
 const d=base();d.people[0].db.gross=70000;d.people[0].db.kind='None';assert(inputErrors(d).some(e=>e.includes('scheme is None')));assert.equal(simulate(d,'fixed',0,zero(d),{detail:true}).rows[0].db,0);d.people[0].db.start='2027-02-30';assert(inputErrors(d).some(e=>e.includes('commencement date')));
});
test('Survivor DB tax uses age at death, not the deceased’s later hypothetical birthday',()=>{
 const make=(dob,taxed)=>{const d=base();d.start='2026-07-01';d.people[0].dob=dob;d.people[0].endAge=63;d.people[0].deathAge=(2027-Number(dob.slice(0,4)));d.people[1].dob='1970-01-01';d.people[1].endAge=58;d.people[0].db.gross=70000;d.people[0].db.survivor=100;d.people[0].db.taxed=taxed;d.people[0].db.untaxed=100-taxed;return d;};
 // Death at 60 makes the taxed element tax-free for an under-60 spouse.
 const a=make('1967-01-01',100);a.people[0].db.start='2027-01-01';const ar=simulate(a,'fixed',0,zero(a),{detail:true});assert(Math.abs(ar.rows.reduce((s,y)=>s+y.tax,0))<.01);
 // Death at 59 leaves the taxed element assessable with a 15% offset, even next year.
 const b=make('1968-01-01',100);b.people[0].db.start='2027-01-01';const br=simulate(b,'fixed',0,zero(b),{detail:true});assert(br.rows.find(y=>y.year===2028).tax>0);
 // Untaxed element stays taxable; death at 60 receives the 10% offset.
 const c=make('1967-01-01',0),e=make('1968-01-01',0);const cr=simulate(c,'fixed',0,zero(c),{detail:true}),er=simulate(e,'fixed',0,zero(e),{detail:true});assert(cr.rows.find(y=>y.year===2027).tax<er.rows.find(y=>y.year===2027).tax);
});
test('UK survivor pension reduction waits until the scheduled lump sum',()=>{
 const d=base();d.people.forEach(p=>p.endAge=63);d.people[0].deathAge=60.5;d.people[0].uk.ongoingGBP=12000;d.people[0].uk.ongoingStart=d.start;d.people[0].uk.survivor=100;d.people[0].uk.reductionGBP=6000;d.people[0].uk.date='2028-01-01';d.people[0].uk.processingDays=0;d.settings.fx=1;const r=simulate(d,'fixed',0,zero(d),{detail:true});assert.equal(r.rows.find(y=>y.year===2027).uk,12000);assert.equal(r.rows.find(y=>y.year===2028).uk,6000);
});
// Date: 2026-10-07. Model: GPT-6. Prompt: Retain the published 67% PSS survivor default; verify pre-60 payments, partial-year totals, explicit commencement, old backups, survivor tax and UK reduction timing.
test('Current-year start and end rounding give twelve-month rows and a full 70000 pension',()=>{
 const d=calendarPlan(base());assert.equal(d.start,`${new Date().getFullYear()}-01-01`);d.people.forEach(p=>{p.dob=`${Number(d.start.slice(0,4))-59}-10-01`;p.endAge=61;});d.people[0].db.gross=70000;const r=simulate(d,'fixed',0,zero(d),{detail:true});assert(r.rows.every(y=>y.months===12));assert(r.rows.every(y=>Math.abs(y.db-70000)<.01));assert.equal(r.rows.length,3);assert.equal(defaults().start.slice(4),'-01-01');
});
test('Both deaths during a year still produce a complete final calendar-year row',()=>{
 const d=calendarPlan(base());const year=Number(d.start.slice(0,4));d.people.forEach(p=>{p.dob=`${year-60}-07-01`;p.endAge=62;p.deathAge=60;});const r=simulate(d,'fixed',12000,zero(d),{detail:true});assert(r.rows.every(y=>y.months===12));assert.equal(r.rows[0].spending,6000);
});
// Date: 2026-10-07. Model: GPT-6. Prompt: Verify current-year January commencement, full-year PSS totals and complete final calendar-year rows.

test('Super access dates follow birth date, owner and selected retirement assumption',async()=>{
 const {birthday,superAccessDate}=await import('../super-access.js');const people=[{dob:'1970-07-20'},{dob:'1973-11-16'}];const a={owner:0,type:'accumulation',accessDate:''};assert.equal(superAccessDate(a,people,'2026-01-01'),'2030-07-20');a.accessMode='retired60';assert.equal(superAccessDate(a,people,'2026-01-01'),'2030-07-20');a.owner=1;assert.equal(superAccessDate(a,people,'2026-01-01'),'2033-11-16');people[1].dob='1974-04-03';assert.equal(superAccessDate(a,people,'2026-01-01'),'2034-04-03');assert.equal(birthday('1960-02-29',65),'2025-02-28');assert.equal(birthday('1960-02-30',65),'');assert.equal(birthday('',60),'');
});
test('Automatic access governs actual withdrawals and pension commencement validation',()=>{
 const d=base();d.assets.cash=0;d.accounts=[{label:'Super',owner:0,type:'accumulation',balance:100000,accessMode:'age65',accessDate:'',pensionDate:'',fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0}];assert.equal(simulate(d,'fixed',12000,zero(d)).success,false);d.accounts[0].accessMode='retired60';assert.equal(simulate(d,'fixed',12000,zero(d)).success,true);d.accounts[0].accessMode='age65';d.accounts[0].pensionDate='2027-01-01';assert(inputErrors(d).some(x=>x.includes('pension commencement precedes')));
});
test('Legacy manual dates remain overrides and missing manual dates are blocked',async()=>{
 const {accessMode,superAccessDate}=await import('../super-access.js');const d=base();const a={label:'Super',owner:0,type:'accumulation',balance:100000,accessDate:'2028-01-01',pensionDate:'',fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0};assert.equal(accessMode(a),'manual');assert.equal(superAccessDate(a,d.people,d.start),'2028-01-01');d.people[0].dob='1967-05-01';assert.equal(superAccessDate(a,d.people,d.start),'2028-01-01');a.accessMode='manual';a.accessDate='';d.accounts=[a];assert(inputErrors(d).some(x=>x.includes('enter the confirmed access date')));
});
// Date: 2026-10-07. Model: GPT-6. Prompt: Verify automatic super dates, owner/DOB updates, leap birthdays, withdrawal eligibility, manual overrides and pension-phase validation.

test('Suggested settlement dates and cash never overwrite confirmed values',async()=>{
 const {applySuggestions,acceptSuggestion,addMonths}=await import('../planning-inputs.js');const d=base();d.housing.earliest='2027-01-31';applySuggestions(d,'housing.earliest');assert.equal(d.housing.expected,'2027-03-31');assert.equal(d.housing.latest,'2027-07-31');assert.equal(addMonths('2028-12-31',2),'2029-02-28');assert.equal(addMonths('2026-02-30',2),'');acceptSuggestion(d,'housing.expected');d.housing.earliest='2027-02-01';applySuggestions(d,'housing.earliest');assert.equal(d.housing.expected,'2027-03-31');assert.equal(d.housing.latest,'2027-08-01');d.assets.cash=null;d.housing.reserved=400000;applySuggestions(d,'housing.reserved');assert.equal(d.assets.cash,400000);acceptSuggestion(d,'assets.cash');d.housing.reserved=450000;applySuggestions(d,'housing.reserved');assert.equal(d.assets.cash,400000);d.assets.cash=0;applySuggestions(d,'housing.reserved');assert.equal(d.assets.cash,0);
});
test('Automatic pension phase follows access and accumulation opt-out suppresses minima',async()=>{
 const {pensionStartDate,dbStartDate}=await import('../super-access.js');const d=base();const a={label:'Super',owner:0,type:'accumulation',balance:100000,accessMode:'retired60',pensionAuto:true,keepAccumulation:false,accessDate:'',pensionDate:'',fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0};d.accounts=[a];assert.equal(pensionStartDate(a,d.people,d.start),'2026-07-01');const r=simulate(d,'fixed',0,zero(d),{detail:true});assert(r.rows[0].withdrawals>0);a.keepAccumulation=true;assert.equal(pensionStartDate(a,d.people,d.start),'');assert.equal(simulate(d,'fixed',0,zero(d),{detail:true}).rows[0].withdrawals,0);a.keepAccumulation=false;a.pensionDate='2027-01-01';assert.equal(pensionStartDate(a,d.people,d.start),'2027-01-01');assert.equal(dbStartDate(d.people[0],d.start),'2021-07-01');
});
test('Failure diagnostics distinguish payment shortfall from final estate reserve',()=>{
 const d=base();d.assets.cash=0;d.spending.essential=12000;const a=simulate(d,'fixed',12000,zero(d),{detail:true});assert.equal(a.firstFailureYear,2026);assert.match(a.firstFailureReason,/cannot be funded/);d.assets.cash=100000;d.spending.essential=0;d.spending.estate=200000;const b=simulate(d,'fixed',0,zero(d));assert.equal(b.firstFailureYear,2027);assert.match(b.firstFailureReason,/estate reserve/);
});
test('Guardrails lifetime median is derived from each path, with 1000-run and 200% defaults',()=>{
 const d=base();d.settings.paths=100;d.spending.desired=20000;d.people.forEach(p=>p.endAge=63);d.spending.essential=5000;const result=compare(d),r=result.results.find(r=>r.strategy==='guardrails'),zs=paths(d,100);const median=a=>{a.sort((x,y)=>x-y);return (a[49]+a[50])/2;};const per=zs.map(z=>{const ys=simulate(d,'guardrails',r.start,z,{detail:true}).rows.map(y=>y.spending/y.infl*12/y.months).sort((a,b)=>a-b);const i=(ys.length-1)/2;return (ys[Math.floor(i)]+ys[Math.ceil(i)])/2;});assert.equal(r.lifetimeMedian,median(per));assert.equal(defaults().settings.paths,1000);assert.equal(defaults().settings.guardMax,200);
});
// Date: 2026-10-09. Model: GPT-6. Prompt: Verify provisional suggestions preserve manual entries, automatic pension minima/opt-out, failure reasons and independently calculated guardrails lifetime medians.

test('Wealth percentiles subtract debt within each path and exclude the principal home',()=>{
 const d=base();d.settings.paths=100;d.assets.cash=200000;d.assets.outside=100000;d.assets.costBasis=100000;d.assets.mix=[{option:'growth',weight:100,real:4,vol:12}];d.assets.debt=20000;d.assets.debtRate=3;d.assets.debtPayment=100;d.assets.propertyValue=120000;d.assets.otherAssets=5000;d.housing.value=900000;d.spending.desired=10000;
 const result=compare(d),zs=paths(d,100);for(const r of result.results){const runs=zs.map(z=>simulate(d,r.strategy,r.start,z,{detail:true}));for(const y of r.rows){const vals=runs.map(run=>{const row=run.rows.find(a=>a.year===y.year);assert.equal(row.wealth,row.assets+d.assets.propertyValue+d.assets.otherAssets-row.debt);return row.wealth/row.infl;}).sort((a,b)=>a-b);for(const [suffix,q] of [['',.5],['10',.1],['90',.9]]){const i=(vals.length-1)*q;assert.equal(y['wealth'+suffix],vals[Math.floor(i)]+(vals[Math.ceil(i)]-vals[Math.floor(i)])*(i%1));}}}
});
// Date: 2026-10-09. Model: GPT-6. Prompt: Verify wealth is financial assets less debts and that its outcome percentiles are calculated per simulation path without the principal home.
