import test from 'node:test';import assert from 'node:assert/strict';
import {defaults,demo} from '../rules.js';import {incomeTax,agePension,mixStats,simulate,paths,settlement,compare,validate} from '../model.js';
function base(){const d=defaults();d.start='2026-07-01';d.people.forEach(p=>{p.dob='1966-07-01';p.endAge=61;p.residenceEligible='no';p.db.gross=0;p.db.verified=true;p.medicare=false;});d.assets.cash=100000;d.assets.outside=0;d.assets.costBasis=0;d.spending.essential=0;d.spending.desired=0;d.spending.reserve=0;d.settings.inflation=0;d.settings.inflationVol=0;d.settings.fxVol=0;d.settings.cashRate=0;d.assets.yield=0;d.assets.mix=[{option:'cash',weight:100,real:0,vol:0}];return d;}
const zero=d=>new Float32Array(paths(d,1)[0].length);
test('Enacted resident first-band tax changes use financial-year commencement',()=>{assert.equal(incomeTax(45000,2026),4020);assert(Math.abs(incomeTax(45000,2027)-3752)<1e-8);assert.equal(incomeTax(18200,2026),0);});
test('Age Pension couples use combined assets with one eligible member',()=>{const p={financial:0,assets:499000,otherIncome:0,eligible:true};assert.equal(agePension(p),933*26);assert.equal(agePension({...p,assets:599000}),933*26-3900);assert.equal(agePension({...p,eligible:false}),0);});
test('Means test uses deeming instead of actual investment yield',()=>{assert(agePension({financial:500000,assets:500000,otherIncome:0,eligible:true})<933*26);});
test('Mix volatility uses covariance',()=>{const d=base();d.settings.correlation=0;const s=mixStats([{option:'a',weight:50,real:4,vol:10},{option:'b',weight:50,real:4,vol:10}],d.settings);assert(Math.abs(s.vol-Math.sqrt(.005))<1e-8);});
test('Zero-return cash funds precisely the requested payments',()=>{const d=base();const r=simulate(d,'fixed',12000,zero(d),{detail:true});assert(r.success);assert(Math.abs(r.endAssets-88000)<.01);assert.equal(r.rows[0].months,6);assert.equal(r.rows[0].spending,6000);});
test('Distributions are not double counted against total return',()=>{const d=base();d.assets.cash=0;d.assets.outside=100000;d.assets.costBasis=100000;d.assets.yield=6;d.assets.mix[0].real=12;const r=simulate(d,'fixed',0,zero(d));assert(Math.abs(r.endAssets-100000*1.01**12)<1);});
test('Account pension minima move assets to cash/outside without consuming them',()=>{const d=base();d.assets.cash=0;d.accounts=[{label:'Test',owner:0,type:'pension',balance:100000,accessDate:d.start,pensionDate:d.start,fee:0,mix:d.assets.mix,changes:[],manualWithdrawal:0}];const r=simulate(d,'fixed',0,zero(d),{detail:true});assert(Math.abs(r.endAssets-100000)<1);assert(r.rows.at(-1).outside>0);assert(r.rows.at(-1).super<100000);});
test('Future allocation schedule applies in the specified January',()=>{const d=base();d.people.forEach(p=>p.endAge=62);d.assets.cash=0;d.assets.outside=100000;d.assets.costBasis=100000;const before=simulate(d,'fixed',0,zero(d));d.assets.changes=[{year:2027,mix:[{option:'cash',weight:100,real:12,vol:0}]}];assert(simulate(d,'fixed',0,zero(d)).endAssets>before.endAssets);});
test('Pending settlement cannot be funded by a later UK receipt',()=>{const d=base();d.assets.cash=10000;d.housing.enabled=true;d.housing.balance=50000;d.housing.expected='2026-08-01';d.housing.earliest='2026-08-01';d.people[0].uk.lumpGBP=50000;d.people[0].uk.date='2026-10-01';d.people[0].uk.taxMode='manual';d.people[0].uk.verified=true;assert(!simulate(d,'fixed',0,zero(d)).settlementSuccess);assert(settlement(d)[0].shortfall>0);});
test('Inheritance is absent in baseline, and included once in smaller/later scenario',()=>{const d=base();d.inheritances=[{amount:10000,mode:'net',currency:'AUD',date:'2026-08-01',lateDate:'2026-09-01'}];assert.equal(simulate(d,'fixed',0,zero(d)).endAssets,100000);d.scenario.inheritance='late';assert.equal(simulate(d,'fixed',0,zero(d)).endAssets,107500);});
test('Unfunded essential-spending floor is recorded as failure',()=>{const d=base();d.assets.cash=0;d.spending.essential=10000;assert(!simulate(d,'guardrails',10000,zero(d)).essentialSuccess);});
test('Mortgage repayments stop when paid off',()=>{const d=base();d.assets.debt=100;d.assets.debtRate=0;d.assets.debtPayment=1000;assert.equal(simulate(d,'fixed',0,zero(d)).endAssets,99900);});
test('Backups reject an invalid schema',()=>{assert.throws(()=>validate({schema:2}));assert.equal(validate(base()).schema,1);});
test('Comparison is deterministic with fixed seed',()=>{const d=demo();d.people.forEach(p=>p.endAge=62);d.settings.paths=100;const a=compare(d),b=compare(d);assert.deepEqual(a.results,b.results);});
// Date: 2026-10-06. Model: GPT-6. Prompt: Validate consequential retirement calculations including tax, means tests, settlement timing, withdrawal conservation and allocation changes.
